language: node_js
node_js:
  - "lts/*"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  fqdn: p5-web.meiamso.me
  keep-history: true
  local-dir: dist/
  on:
    branch: master
